version: '3'
services:
  #CloudBees Jenkins Team
  #https://hub.docker.com/r/cloudbees/cloudbees-jenkins-team/
  cjt:
    container_name: cjt
    build: ./cjt
    image: cjt:latest
    #https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties
    environment:
      JENKINS_SLAVE_AGENT_PORT: "50000"
      JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=America/New_York"
      SONAR_USER: ${SONAR_USER}
      SONAR_PASSWORD: ${SONAR_PASSWORD}
      DOCKERHUB_USER: ${DOCKERHUB_USER}
      DOCKERHUB_PASSWORD: ${DOCKERHUB_PASSWORD}
    ports:
      - "9090:8080" #host:container
    volumes:
      - ./cjt/data:/var/jenkins_home #persist all the data
      - /var/run/docker.sock:/var/run/docker.sock #Docker on Docker
      - ${USER_M2}:/root/.m2 #requires .env file

networks:
  default:
    external:
      name: cjt-network
